"""Generate src/build_version.h from git state at build time (DEC-035).

Per-env independent versioning, mirroring hapbeat-device-firmware:
  - Base semver comes from `firmware-versions.json` (`envs[$PIOENV]`), the single
    source of truth (this repo's `_repoShort` is "tx").
  - Release tags are namespaced per env: `tx/<env>/vX.Y.Z`. The dev counter `dN`
    is per-env — bumping `m5stack_audio_tx` does not advance `esp32`'s N.

Format:
  - Tag-exact AND clean (HEAD == tx/esp32/v0.1.0): FIRMWARE_VERSION = "0.1.0"
  - Dev commit:                                    FIRMWARE_VERSION = "<base>d<N>"

Fallback: when $PIOENV is empty the script reverts to the legacy GLOBAL `v*`
scheme (avoids the `tx//v*` double-slash that would match nothing). When the
env is missing from firmware-versions.json it warns and uses FALLBACK_BASE.

The generated header is gitignored — every build computes it fresh.
"""
from __future__ import annotations

import json
import os
import subprocess

Import("env")  # type: ignore  # noqa: F821 — provided by PlatformIO

# Last-resort base when firmware-versions.json is missing/unreadable or the env
# has no entry. firmware-versions.json is authoritative; this only keeps the
# build from failing (with a warning).
FALLBACK_BASE = "0.0.0"


def _run_git(args: list[str], cwd: str) -> str | None:
    try:
        out = subprocess.check_output(
            ["git", *args], cwd=cwd, stderr=subprocess.DEVNULL
        )
        return out.decode("utf-8", errors="replace").strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _read_versions_json(
    project_dir: str, env_name: str
) -> tuple[str | None, str | None]:
    """Return (base_semver_for_env, repo_short) from firmware-versions.json."""
    path = os.path.join(project_dir, "firmware-versions.json")
    if not os.path.isfile(path):
        return (None, None)
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, ValueError) as e:
        print(f"[build_version] WARNING: cannot read firmware-versions.json: {e}")
        return (None, None)
    repo_short = data.get("_repoShort")
    base = (data.get("envs") or {}).get(env_name)
    return (base, repo_short)


def _is_dirty(project_dir: str) -> bool:
    out = _run_git(
        ["status", "--porcelain", "--untracked-files=no"], project_dir
    )
    return bool(out)


def _compute_version(
    project_dir: str, base: str, pattern: str, strip_tag
) -> tuple[str, str]:
    dirty = _is_dirty(project_dir)
    if not dirty:
        exact = _run_git(
            ["describe", "--tags", "--exact-match", "--match", pattern],
            project_dir,
        )
        if exact:
            return strip_tag(exact), f"tag-exact ({exact})"
    last_tag = _run_git(
        ["describe", "--tags", "--abbrev=0", "--match", pattern], project_dir
    )
    if last_tag:
        n = _run_git(["rev-list", "--count", f"{last_tag}..HEAD"], project_dir)
    else:
        n = _run_git(["rev-list", "--count", "HEAD"], project_dir)
        last_tag = "<none>"
    if n is None:
        return base, "git-unavailable (base only)"
    note = " +dirty" if dirty else ""
    return f"{base}d{n}", f"dev (since {last_tag}, +{n} commits{note})"


def _short_sha(project_dir: str) -> str:
    sha = _run_git(["rev-parse", "--short", "HEAD"], project_dir)
    return sha or "unknown"


def main() -> None:
    project_dir = env.subst("$PROJECT_DIR")  # type: ignore  # noqa: F821
    env_name = (env.subst("$PIOENV") or "").strip()  # type: ignore  # noqa: F821
    out_path = os.path.join(project_dir, "src", "build_version.h")

    base_json, repo_short = _read_versions_json(project_dir, env_name)

    if env_name and repo_short:
        if base_json is None:
            print(
                f"[build_version] WARNING: env '{env_name}' not in "
                f"firmware-versions.json — using fallback {FALLBACK_BASE}. "
                "Add it to avoid an fwVersion collision (DEC-035 §9-12)."
            )
        base = base_json or FALLBACK_BASE
        pattern = f"{repo_short}/{env_name}/v*"

        def strip_tag(t: str) -> str:
            return t.rsplit("/v", 1)[-1]  # tx/esp32/v0.1.0 → 0.1.0
    else:
        base = base_json or FALLBACK_BASE
        pattern = "v*"

        def strip_tag(t: str) -> str:
            return t.lstrip("v")

    fw_version, source = _compute_version(project_dir, base, pattern, strip_tag)
    sha = _short_sha(project_dir)

    header = (
        "// Auto-generated by scripts/build_version.py — DO NOT EDIT.\n"
        "// This file is gitignored; it is regenerated on every build.\n"
        f"// Source: {source}\n"
        "#pragma once\n"
        f'#define FIRMWARE_VERSION "{fw_version}"\n'
        f'#define BUILD_COMMIT_SHA "{sha}"\n'
    )

    existing = ""
    if os.path.isfile(out_path):
        try:
            with open(out_path, encoding="utf-8") as f:
                existing = f.read()
        except OSError:
            pass
    if existing != header:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(header)

    print(
        f"[build_version] env='{env_name or '<none>'}' "
        f"FIRMWARE_VERSION='{fw_version}' sha={sha} ({source})"
    )


main()
